apiVersion: v1
kind: Service
metadata:
  name: mymicroservice
  labels:
    app: mymicroservice
spec:
  type: LoadBalancer
  selector:
    app: mymicroservice
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 3000